# Use root/example as user/password credentials
version: '3.1'

services:
  
  # Identity Provider
  idp:
    image: compose.idp:latest
    build: 
      context: .
      dockerfile: "src/IdentityServerAspNetIdentity/Dockerfile"
    depends_on:
      - db
    restart: on-failure
    ports:
      - "4001:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/idp.pfx
    volumes:
      - ./src/_Certificates:/https:ro
  
  idp2:
    image: compose.idp:latest
    build: 
      context: .
      dockerfile: "src/IdentityServerAspNetIdentity/Dockerfile"
    depends_on:
      - db
    restart: on-failure
    ports:
      - "4003:80"
      - "5003:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/idp.pfx
    volumes:
      - ./src/_Certificates:/https:ro

  idp3:
    image: compose.idp:latest
    build: 
      context: .
      dockerfile: "src/IdentityServerAspNetIdentity/Dockerfile"
    depends_on:
      - db
    restart: on-failure
    ports:
      - "4004:80"
      - "5004:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/idp.pfx
    volumes:
      - ./src/_Certificates:/https:ro
     
  # Service Provider 
  sp:
    image: compose.sp:latest
    build:
      context: .
      dockerfile: "src/AjourBuildMock/Dockerfile"
    depends_on:
      - db
    restart: on-failure
    ports:
      - "4002:80"
      - "5002:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/sp.pfx
    volumes:
      - ./src/_Certificates:/https:ro
    
  # DB for the Service Provider
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
        
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  
  # Loadbalancer
  loadbalancer:
    build: ./loadbalancer
    ports:
      - "8888:80"
      - "5005:443"
    depends_on:
      - idp
      - idp2
      - idp3