# Use root/example as user/password credentials
version: '3.1'

services:
  
  # Identity Provider
  idp:
    image: compose.idp:latest
    build: 
      context: .
      dockerfile: "src/IdentityServerAspNetIdentity/Dockerfile"
    depends_on:
      - db
      - cache
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/idp.pfx
      - AJOUR_IS_CONTAINERIZED=true
      - SERedis_ClientCertPassword=1234
      - SERedis_ClientCertPfxPath=/https/redis.pfx
    volumes:
      - ./src/_Certificates:/https:ro
     
  # Service Provider 
  sp:
    image: compose.sp:latest
    build:
      context: .
      dockerfile: "src/AjourBuildMock/Dockerfile"
    depends_on:
      - db
    restart: on-failure
    ports:
      - "4002:80"
      - "5002:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/sp.pfx
    volumes:
      - ./src/_Certificates:/https:ro
    
  # DB for the Service Provider
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
  
  # Redis Cache
  cache:
    image: redis
    restart: on-failure
    ports:
      - '6379:6379'
    volumes:
      - ./loadbalancer/redis.conf:/tmp/conf/redis.conf:ro
      - ./loadbalancer/certificates/redis:/tmp/certificates/redis:ro
      - ./src/_Certificates/myCA.crt:/tmp/certificates/ca/myCA.crt:ro
    command: redis-server /tmp/conf/redis.conf --loglevel debug
  
  # Loadbalancer
  loadbalancer:
    build: 
      context: .
      dockerfile: "loadbalancer/Dockerfile"
    ports:
      - "8888:80"
      - "5001:443"
    depends_on:
      - idp